### PR TITLE
Group member data source

### PR DESCRIPTION
**Pull request by asleepingpanda**
### Recordings
[Edit Group Member Note](https://www.loom.com/share/890a811f1dcf457bac6a63c93e6b189c)
[Edit Group Member Status](https://www.loom.com/share/67b457f5dec84d428f9461eb629ffe4a)

### CODE REVIEW

**Comment by codingwithlis** [comment]
this is a test comment

**Comment by dzwood** [comment]
@asleepingpanda Looks like there's some conflicts 👀

**Comment by dzwood** [comment]
@asleepingpanda everything looks good to me on my end, we'll just need to update this to a PR (it's still a Draft). We should be good to merge :)

**Review by dzwood — APPROVED** [review]
Working on my end!

**Pull request merged**
