### PR TITLE
[CFDP-927] My dream teams feature

### PR DESCRIPTION
**Pull request by asleepingpanda**
Wanted to get some thoughts on this.

**HMW** 
Introduce a Groups Interface into the GQL schema without breaking any of the current Groups schema that's currently live

**Why?**
Like Content Items that have unique expressions of the interface (Universal, Media, Event, etc), we want to be able to use the base Group interface as a commonality for rendering simple components like Cards. When navigating to a Group Single, we want a simple/easy way to conditionally render UI items or reorder the Group Single while still being able to use the common base items like Group Members, title, and so on.

### CODE REVIEW

**Comment by asleepingpanda** [comment]
@jordanwade this is just a first pass at this and isn't meant to be merged as is. I'm not in love with the name `GroupType` for the interface. Ideally, `Group` would be the interface and then `SmallGroup` or `StandardGroup` or something would be the default type, but I think that might mess up the clients that are already expecting certain field types for the `Group` type?

**Comment by jordanwade** [comment]
@asleepingpanda you mentioned this word in your PR description a couple times. What about `GroupBase` or if you want `Group`. In typescript I've seen a lot of interface names just prefixed with `I` so you could name your interface `IGroup` then you could also apply that pattern across all your interfaces. 

```
type VolunteerGroup implements IGroup & Node {}

type Group implements IGroup {}
```

**Comment by asleepingpanda** [comment]
Ooo! I like `GroupBase` or even `GroupItem` to keep in line with the `ContentItem` interface. Before merging anything final, 2 questions for ya

1. Is adding an interface to the existing `Group` schema at all a risk with it being in production already?
2. Is it possible/worth renaming `Group` to be `CommunityGroup` or `SmallGroup` or something like that? _(just asking cause we are now adding more specific group types like VolunteerGroup. not at all a make or break, though. Just curious.)_

**Comment by jordanwade** [comment]
@asleepingpanda do you think this is ready for a review or is it still in a`Do Not Merge` state?

**Pull request merged**
