### PR TITLE
New `people` field for GroupItem

### PR DESCRIPTION
**Pull request by asleepingpanda**
Enables pagination for people in a group. Filterable by Leaders and non-leaders

@jordanwade this should be 100% backwards compatible, but I wanted to run it by you before merging

### CODE REVIEW

**Comment by jordanwade** [comment]
@asleepingpanda is there any specific steps to test this PR?

**Comment by asleepingpanda** [comment]
Just insure that all your avatar based UI still works as expected

**Review by jordanwade — CHANGES_REQUESTED** [review]
Looks good besides the pixelated member photos. 

With our growing team size how do you prefer to track changes to the api that need to be implemented on the client apps, Github issues, Basecamp, other? Looks like we need update our queries to use `people` instead `members`.

**Comment by asleepingpanda** [comment]
Yeah so group members aren't showing on the web app, so we should be safe there for the time being

Good catch on the pixelation! Was using that for testing cause it dramatically lowered load times. Lol

**Review by jordanwade — APPROVED** [review]

**Pull request merged**
