### PR TITLE
Global Search

### LINKED ISSUE #284: Index Event content items for search
`EventContentItems` are not currently indexed for search. They should show when relevant in results.

### PR DESCRIPTION
**Pull request by lmommaerts**
## DESCRIPTION
In conjunction with https://github.com/christfellowshipchurch/web-app-v2/pull/297

### 1. What does this PR do, or why is it needed?
- Adds Events to search
- Adds an array of hardcoded items that get added to the Algolia index
- Adds an object of additional attributes for specified items. This can be used to add priority tags to items that aren't hardcoded, or any other attributes that may be added to the index in the future
- Adds a priorityTags attribute to the index
- Cleans up some linter problems

## SCREENSHOTS/GIFS

| iOS | Android | Web |
| --- | ------- | --- |
|     |         |     |

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes #284 #286 
- [ ] No new warnings in tests, storybook, or apps
- [ ] Assign relevant reviewers
- [ ] Upload GIF(s) of iOS, Android, Web
- [ ] Get one peer approval before merging

## REVIEW:

**Manual QA**

- [ ] QA branch on iOS and ensure it looks/behaves as expected
- [ ] QA branch on Android and ensure it looks/behaves as expected
- [ ] QA branch on Web and ensure it looks/behaves as expected

**Code Review**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by asleepingpanda** [comment]
@lmommaerts I think I'm following what the `priorityTags` are, but I just want to confirm.

Is this intended to be a field inside of Rock that CM's can manually set? Or is this more of a calculated field?

**Comment by lmommaerts** [comment]
Right now, it's just being used on the `groups` item to make it a priority when the search term `groups` is used. It _could_ be something that gets added to Rock, and then indexed, but it's not necessary. If you want to add it to existing content items without  adding a Rock field, you can use ADDITIONAL_ITEM_ATTRIBUTES with `[itemId]: { priorityTags: [...] }`.

**Comment by asleepingpanda** [comment]
Yeah I like that convention a lot. My only concern with this PR at the moment is that it will require a client-side update to enable to ability to navigate to the indexed Url's (as stored in the related node).

Is there any way for us to insure that we do _not_ index anything other than Content Items until I can get the client-side navigation patch up?

**Comment by asleepingpanda** [comment]
Scope of this was changed a bit, so I copied the changes over to another branch. Closing

**Pull request closed without merging**
